""" Processor module for fprime-yamcs-tlmchan

Svc.TlmChan aggregates multiple telemetry channel records (id, time, value) into a single
downlinked packet. The XTCE generated for YAMCS models one channel per packet keyed on the
first channel id, so YAMCS only decodes the first record of each aggregate packet.

This processor subscribes to the aggregate telemetry channel container, walks every record
in each packet using the F Prime dictionary, and re-injects each record beyond the first as
a standalone single-record space packet on a UDP telemetry link. YAMCS then decodes each
injected packet through its normal XTCE path, publishing every channel as a parameter.

@author LeStarch

Copyright 2026 LeStarch

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import socket
import struct
import time
from pathlib import Path
from typing import List

from yamcs.client import YamcsClient
from yamcs.client import Packet

# FPrime imports
from fprime_gds.common.loaders.ch_json_loader import ChJsonLoader
from fprime_gds.common.decoders.ch_decoder import ChDecoder
from fprime_gds.common.models.serialize.time_type import TimeType
from fprime_gds.common.utils.config_manager import ConfigManager
from .logging import logger


class FPrimeTlmChanProcessor:
    """
    Splits aggregate F Prime telemetry channel packets into single-record packets for YAMCS
    """

    # FPrime packet structure constants
    SPACE_PACKET_HEADER_LEN = 6
    FW_PACKET_DESCRIPTOR_SIZE = 2

    # FPrime APID for telemetry channels (from ComCfg.fpp)
    APID_TLM_CHAN = 1

    # XTCE container matching F´ aggregate telemetry channel packets (generated by fprime-xtce)
    CHANNEL_CONTAINER = "FPrimeTelemetryChannel"

    # Channel record data starts after: SPACE_PACKET_HEADER + FwPacketDescriptorType
    CHANNEL_DATA_OFFSET = SPACE_PACKET_HEADER_LEN + FW_PACKET_DESCRIPTOR_SIZE

    # CCSDS sequence count is 14 bits
    SEQUENCE_COUNT_MODULO = 0x4000

    def __init__(self, yamcs_url: str, yamcs_instance: str, dictionary_path: str,
                 inject_host: str, inject_port: int):
        """
        Initialize the FPrime TlmChan Processor

        Args:
            yamcs_url: URL of the YAMCS server (e.g., 'http://localhost:8090')
            yamcs_instance: YAMCS instance name (e.g., 'myproject')
            dictionary_path: Path to the FPrime topology dictionary JSON file
            inject_host: Host to send split single-record telemetry packets to
            inject_port: UDP port of the YAMCS telemetry packet link for split packets
        """
        self.yamcs_url = yamcs_url
        self.yamcs_instance = yamcs_instance
        self.dictionary_path = Path(dictionary_path)
        self.inject_address = (inject_host, inject_port)
        self.inject_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.sequence_count = 0

        # Initialize YAMCS client
        logger.info(f"Connecting to YAMCS at {yamcs_url}, instance: {yamcs_instance}")
        self.yamcs_client = YamcsClient(yamcs_url)
        self.processor_client = self.yamcs_client.get_processor(
            instance=yamcs_instance,
            processor='realtime'
        )

        # Initialize FPrime channel decoder
        logger.info(f"Loading FPrime dictionary from {dictionary_path}")
        self._init_fprime_decoder()

    def _init_fprime_decoder(self):
        """Initialize the FPrime channel decoder with the topology dictionary"""
        if not self.dictionary_path.exists():
            raise FileNotFoundError(f"Dictionary not found: {self.dictionary_path}")

        # Load the channel dictionary
        channel_loader = ChJsonLoader(self.dictionary_path)
        self.channel_dict = channel_loader.get_id_dict(str(self.dictionary_path))

        # Create the channel decoder (validates records while walking them)
        self.channel_decoder = ChDecoder(self.channel_dict)
        logger.info(f"Loaded {len(self.channel_dict)} channel definitions")

    def _split_records(self, record_data: bytes) -> List[bytes]:
        """
        Split aggregate channel record data into individual raw records

        Args:
            record_data: Concatenated (id, time, value) channel records

        Returns:
            List of raw record byte strings, one per channel record
        """
        records = []
        id_obj = ConfigManager().get_type("FwChanIdType")()
        ptr = 0
        while ptr < len(record_data):
            start = ptr
            id_obj.deserialize(record_data, ptr)
            ptr += id_obj.getSize()
            ch_time = TimeType()
            ch_time.deserialize(record_data, ptr)
            ptr += ch_time.getSize()
            template = self.channel_dict.get(id_obj.val)
            if template is None:
                raise ValueError(f"Channel id {id_obj.val} not found in dictionary")
            val_obj = ChDecoder.decode_ch_val(record_data, ptr, template)
            ptr += val_obj.getSize()
            records.append(record_data[start:ptr])
        return records

    def _inject_record(self, descriptor: bytes, record: bytes):
        """
        Send a single channel record to YAMCS as a standalone space packet

        Args:
            descriptor: The FwPacketDescriptorType bytes from the original packet
            record: Raw (id, time, value) record bytes
        """
        payload = descriptor + record
        self.sequence_count = (self.sequence_count + 1) % self.SEQUENCE_COUNT_MODULO
        header = struct.pack(
            ">HHH",
            (self.APID_TLM_CHAN & 0x07FF),
            0xC000 | self.sequence_count,
            len(payload) - 1,
        )
        self.inject_socket.sendto(header + payload, self.inject_address)

    def _process_channel_packet(self, tm_packet: Packet):
        """
        Process a single aggregate FPrime telemetry channel packet

        Args:
            tm_packet: YAMCS Packet object
        """
        try:
            packet_data = tm_packet.binary

            # Verify APID
            apid_seqcount = struct.unpack('>I', packet_data[0:4])[0]
            apid = (apid_seqcount >> 16) & 0x07FF

            if apid != self.APID_TLM_CHAN:
                logger.debug(f"Skipping non-channel packet with APID {apid}")
                return

            if len(packet_data) <= self.CHANNEL_DATA_OFFSET:
                logger.warning(f"Packet too short: {len(packet_data)} bytes")
                return

            descriptor = packet_data[self.SPACE_PACKET_HEADER_LEN:self.CHANNEL_DATA_OFFSET]
            records = self._split_records(packet_data[self.CHANNEL_DATA_OFFSET:])

            # YAMCS already decoded the first record through the XTCE channel containers;
            # single-record packets (including re-injected ones) need no further splitting
            for record in records[1:]:
                self._inject_record(descriptor, record)

        except Exception as e:
            logger.error(f"Error processing channel packet: {e}", exc_info=True)

    def _channel_container_name(self) -> str:
        """Resolve the qualified name of the F´ aggregate channel container in the MDB"""
        mdb = self.yamcs_client.get_mdb(self.yamcs_instance)
        for container in mdb.list_containers():
            if container.qualified_name.endswith("/" + self.CHANNEL_CONTAINER):
                return container.qualified_name
        raise RuntimeError(
            f"No '{self.CHANNEL_CONTAINER}' container found in the MDB")

    def start(self):
        """
        Start the processor and subscribe to the aggregate channel container

        Subscribing to the FPrimeTelemetryChannel container (rather than all packets)
        filters server-side, so only telemetry channel packets cross the WebSocket.
        """
        logger.info("Starting FPrime TlmChan Processor")
        container = self._channel_container_name()
        logger.info(f"Subscribing to container {container} (APID {self.APID_TLM_CHAN})")
        logger.info(f"Re-injecting split records to udp://{self.inject_address[0]}:{self.inject_address[1]}")

        try:
            subscription = self.processor_client.create_container_subscription(
                containers=[container],
                on_data=self._process_channel_packet,
            )

            logger.info("TlmChan processor running. Press Ctrl+C to stop.")

            # Exit when the subscription dies so the supervising
            # ProcessRunner (restart: always) can start a fresh instance
            while not subscription.done():
                time.sleep(1)
            logger.error("Subscription terminated; exiting for restart")
            raise RuntimeError(subscription.exception() or "subscription closed")

        except KeyboardInterrupt:
            logger.info("Shutting down TlmChan processor")
        except Exception as e:
            logger.error(f"Error in TlmChan processor: {e}", exc_info=True)
            raise
